# ASP.NET Core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.0.100-preview4-011223'
- script: dotnet build --configuration $(buildConfiguration) ReusableComponents/ReusableComponents.sln
  displayName: 'dotnet build $(buildConfiguration) ReusableComponents'
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'blazordist'